import { motion } from "framer-motion";
import { ExternalLink, ArrowRight, CheckCircle2, Filter } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { portfolioProjects } from "@/lib/constants";
import { useMemo, useState } from "react";
import Seo from "@/components/Seo";

const filters = ["All", "Business", "Marketplace", "Education", "Organisation", "E-Commerce", "Web Development"];
const fadeIn = { hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0, transition: { duration: 0.4 } } };

export default function PortfolioPage() {
  const [activeFilter, setActiveFilter] = useState("All");
  const visibleProjects = useMemo(() => activeFilter === "All" ? portfolioProjects : portfolioProjects.filter((project) => project.category.includes(activeFilter) || project.tags.some((tag) => tag.includes(activeFilter))), [activeFilter]);
  return (
    <>
      <Seo title="Website Design Portfolio Kenya | KenyaAdverts Projects" description="Explore KenyaAdverts website and web application projects across business, education, marketplaces, organisations, e-commerce and custom digital products." path="/portfolio" />
      <section className="pt-32 pb-16"><div className="container mx-auto px-4 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="max-w-3xl"><span className="text-sm font-semibold text-primary uppercase tracking-widest">Portfolio</span><h1 className="mt-4 text-4xl md:text-6xl font-display font-extrabold">Websites, platforms & <span className="text-gradient-primary">digital products.</span></h1><p className="mt-5 text-lg text-muted-foreground leading-relaxed">Explore our work across business, education, marketplaces, organisations, e-commerce and custom digital projects.</p></motion.div></div></section>
      <section className="pb-20"><div className="container mx-auto px-4 lg:px-8"><div className="flex flex-wrap gap-2 mb-10 items-center"><Filter className="h-4 w-4 text-muted-foreground mr-1" />{filters.map((filter) => <button key={filter} onClick={() => setActiveFilter(filter)} className={`px-4 py-2 rounded-full text-sm font-medium border transition-all ${activeFilter === filter ? "bg-primary text-primary-foreground border-primary" : "bg-card border-border text-muted-foreground hover:text-foreground hover:border-primary/30"}`}>{filter}</button>)}</div>{visibleProjects.length > 0 ? <div className="grid md:grid-cols-2 gap-7">{visibleProjects.map((project) => <motion.article key={project.id} variants={fadeIn} initial="hidden" whileInView="visible" viewport={{ once: true }} className="group rounded-2xl overflow-hidden bg-card border border-border hover:border-primary/30 hover:-translate-y-1 transition-all"><div className="aspect-[16/9] overflow-hidden bg-muted">{project.image && <img src={project.image} alt={`${project.title} website project`} loading="lazy" className="w-full h-full object-cover group-hover:scale-[1.03] transition-transform duration-500" />}</div><div className="p-6"><div className="flex items-center gap-2"><span className="text-xs font-semibold text-primary uppercase tracking-wider">{project.category}</span><span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><CheckCircle2 className="h-3 w-3" /> Live</span></div><h2 className="mt-2 text-2xl font-display font-bold">{project.title}</h2><p className="mt-3 text-sm text-muted-foreground leading-relaxed">{project.description}</p><div className="mt-4 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="px-2.5 py-1 rounded-full text-xs bg-muted text-muted-foreground">{tag}</span>)}</div><a href={project.url} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center text-sm font-semibold text-primary">View live project <ExternalLink className="ml-1.5 h-3.5 w-3.5" /></a></div></motion.article>)}</div> : <div className="py-20 text-center text-muted-foreground">No projects in this category yet. <button onClick={() => setActiveFilter("All")} className="text-primary font-semibold">View all projects</button></div>}</div></section>
      <section className="py-24 bg-muted/30"><div className="container mx-auto px-4 lg:px-8"><div className="max-w-3xl mx-auto text-center"><span className="text-sm font-semibold text-primary uppercase tracking-widest">Your next project</span><h2 className="mt-3 text-3xl md:text-5xl font-display font-extrabold">We can build something for your industry too.</h2><p className="mt-4 text-muted-foreground text-lg">Business, school, shop, organisation, personal brand or a completely custom system — tell us what you need.</p><Button asChild size="lg" className="mt-8 bg-gradient-primary"><Link to="/order">Start a Project <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>
    </>
  );
}
