import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { CheckCircle2, ArrowRight, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { WHATSAPP_ORDER_URL } from "@/lib/constants";

const plans = [
  { name: "Starter Website", price: "From KES 5,000", description: "A clean, mobile-friendly website for a small business, personal brand or simple organisation.", features: ["Up to 5 core pages", "Responsive design", "WhatsApp/contact CTA", "Basic SEO setup", "Domain & hosting guidance"] },
  { name: "Business Website", price: "From KES 15,000", description: "A more tailored website for businesses and organisations that need stronger branding and lead generation.", features: ["Custom page structure", "Professional responsive design", "Enquiry/contact forms", "Google & social integration", "SEO-ready structure", "Content guidance"] },
  { name: "E-Commerce / Web App", price: "Custom quote", description: "For online shops, marketplaces, portals, dashboards and systems with custom functionality.", features: ["Custom functionality", "M-Pesa/payment integration", "Database & admin features", "User accounts where needed", "Third-party/API integrations", "Post-launch support options"] },
];

export default function PricingPage() {
  return (
    <>
      <section className="pt-32 pb-16"><div className="container mx-auto px-4 lg:px-8 text-center"><span className="text-sm font-semibold text-primary uppercase tracking-widest">Pricing</span><h1 className="mt-4 text-4xl md:text-6xl font-display font-extrabold">Choose a starting point.</h1><p className="mt-5 text-lg text-muted-foreground max-w-2xl mx-auto">Every project is different. These starting points make it easier to understand the range before we discuss your exact pages and features.</p></div></section>
      <section className="pb-24"><div className="container mx-auto px-4 lg:px-8"><div className="grid md:grid-cols-3 gap-6 max-w-6xl mx-auto">{plans.map((plan, i) => <motion.article key={plan.name} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.08 }} className={`p-7 rounded-2xl bg-card border ${i === 1 ? "border-primary/50 ring-1 ring-primary/10" : "border-border"}`}><h2 className="text-xl font-display font-bold">{plan.name}</h2><div className="mt-5 text-3xl font-display font-extrabold text-primary">{plan.price}</div><p className="mt-4 text-sm text-muted-foreground leading-relaxed">{plan.description}</p><div className="mt-6 space-y-3">{plan.features.map((feature) => <div key={feature} className="flex items-start gap-2 text-sm"><CheckCircle2 className="h-4 w-4 text-primary mt-0.5 shrink-0" />{feature}</div>)}</div><Button asChild className={`w-full mt-8 ${i === 1 ? "bg-gradient-primary" : ""}`} variant={i === 1 ? "default" : "outline"}><Link to="/order">Get a quote <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></motion.article>)}</div><div className="mt-12 text-center"><p className="text-sm text-muted-foreground">Have a specific budget or idea?</p><a href={WHATSAPP_ORDER_URL} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex items-center gap-2 text-primary font-semibold">Discuss it on WhatsApp <MessageCircle className="h-4 w-4" /></a></div></div></section>
      <section className="py-20 bg-muted/30"><div className="container mx-auto px-4 lg:px-8 max-w-4xl"><div className="grid md:grid-cols-3 gap-5 text-center"><div className="p-6 rounded-2xl bg-card border border-border"><h3 className="font-display font-bold">Clear scope</h3><p className="mt-2 text-sm text-muted-foreground">We agree on pages and features before development.</p></div><div className="p-6 rounded-2xl bg-card border border-border"><h3 className="font-display font-bold">Flexible projects</h3><p className="mt-2 text-sm text-muted-foreground">Small website or larger system — scope can grow with your needs.</p></div><div className="p-6 rounded-2xl bg-card border border-border"><h3 className="font-display font-bold">Direct support</h3><p className="mt-2 text-sm text-muted-foreground">Stay in touch through WhatsApp during the project.</p></div></div></div></section>
    </>
  );
}
